---
title: "Tesouro Gerencial"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: ["twitter", "facebook", "menu"]
    runtime: shiny
    

---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(DT)
library(flexdashboard)
library(knitr)
library(shiny)
library(shinyWidgets)
library(lubridate)
options(scipen=999)


```



```{r}
tg <- read_excel ("tg.xlsx")

# alterar os nomes das colunas

colnames(tg)<- c("fase","fase_cod", "gnd_cod","gnd" , "ano_lan", "ano_emp", "org_uo_cod", "org_uo", "org_exec_cod", "org_exec", "saldo" )

# excluir registro com problema

tg<- tg%>% filter (ano_emp != "'-7" & org_uo_cod != "'-7" & ano_emp != "'-9")

tg$ano_lan<- as.integer(tg$ano_lan)
tg$ano_emp<- as.integer(tg$ano_emp)

# alterar nome das fases da execução da despesa

tg<- tg%>%
 mutate(fase = case_when(
 fase == "DESPESAS EMPENHADAS (CONTROLE EMPENHO)" ~ "empenhado",
 fase == "DESPESAS LIQUIDADAS (CONTROLE EMPENHO)" ~ "liquidado",
 fase == "DESPESAS PAGAS (CONTROLE EMPENHO)" ~ "pago",
 fase == "RESTOS A PAGAR PAGOS (PROC E N PROC)" ~ "RP pago"
 
))


# alterar dos grupos da despesa
tg<- tg%>%
 mutate(gnd = case_when(
 gnd == "AMORTIZACAO/REFINANCIAMENTO DA DIVIDA" ~ "amortização da dívida",
 gnd == "INVERSOES FINANCEIRAS" ~ "inversões financeiras",
 gnd == "INVESTIMENTOS" ~ "investimentos",
 gnd == "JUROS E ENCARGOS DA DIVIDA" ~ "juros da dívida",
 gnd == "OUTRAS DESPESAS CORRENTES" ~ "outras despesas correntes",
 gnd == "PESSOAL E ENCARGOS SOCIAIS" ~ "pessoal e encargos sociais"
 
))


#incluir apelido para órgãos máximos executores
tg<- tg %>%
  mutate (org_exec_nome = case_when (
org_exec == "ADVOCACIA-GERAL DA UNIAO" ~ "Advocacia Geral da União",
org_exec == "CAMARA DOS DEPUTADOS" ~ "Câmara dos Deputados",
org_exec == "CONSELHO NACIONAL DE JUSTICA" ~ "CNJ",
org_exec == "CONSELHO NACIONAL DO MINISTERIO PUBLICO" ~ "CNMP",
org_exec == "CONTROLADORIA-GERAL DA UNIAO" ~ "CGU",
org_exec == "DEFENSORIA PUBLICA DA UNIAO" ~ "DPU",
org_exec == "JUSTICA DO DISTRITO FEDERAL E DOS TERRITORIOS" ~ "JDFT",
org_exec == "JUSTICA DO TRABALHO" ~ "Justiça do Trabalho",
org_exec == "JUSTICA ELEITORAL" ~ "Justiça Eleitorial",
org_exec == "JUSTICA FEDERAL" ~ "Justiça Federal",
org_exec == "JUSTICA MILITAR" ~ "Justiça Militar",
org_exec == "M.DAS MULH.,DA IG.RACIAL DA JUVENT.E DIR.HUM." ~ "Ministério das Mulheres",
org_exec == "MINIST. DA AGRICUL.,PECUARIA E ABASTECIMENTO" ~ "Ministério da Agricultura",
org_exec == "MINIST. DA INDUSTRIA, COM.EXTERIOR E SERVICOS" ~ "Ministério da Indústria",
org_exec == "MINIST. DO PLANEJAMENTO, DESENVOLV. E GESTAO" ~ "Ministério da Planejamento",
org_exec == "MINIST. MULHER, FAMILIA E DIREITOS HUMANOS" ~ "Ministério da Mulher.",
org_exec == "MINIST.DA CIENCIA,TECNOL.,INOV.E COMUNICACOES" ~ "Ministério da Ciência",
org_exec == "MINISTERIO DA CIDADANIA" ~ "Ministério da Cidadania",
org_exec == "MINISTERIO DA CULTURA" ~ "Ministério da Cultural",
org_exec == "MINISTERIO DA DEFESA" ~ "Ministério da Defesa",
org_exec == "MINISTERIO DA ECONOMIA" ~ "Ministério da Economia",
org_exec == "MINISTERIO DA EDUCACAO" ~ "Ministério da Educação",
org_exec == "MINISTERIO DA INFRAESTRUTURA" ~ "Ministério da Infraestrutura",
org_exec == "MINISTERIO DA JUSTICA E SEGURANCA PUBLICA" ~ "Ministério da Justiça",
org_exec == "MINISTERIO DA PESCA E AQUICULTURA" ~ "Ministério da Pesca",
org_exec == "MINISTERIO DA PREVIDENCIA SOCIAL" ~ "MPS",
org_exec == "MINISTERIO DA SAUDE" ~ "Ministério da Saúde",
org_exec == "MINISTERIO DA SEGURANCA PUBLICA" ~ "Ministério da Segurança",
org_exec == "MINISTERIO DAS CIDADES" ~ "Ministério das Cidades",
org_exec == "MINISTERIO DAS COMUNICACOES" ~ "Ministério das Comunicações",
org_exec == "MINISTERIO DAS RELACOES EXTERIORES" ~ "MRE",
org_exec == "MINISTERIO DE MINAS E ENERGIA" ~ "Ministério de Minas e Energia",
org_exec == "MINISTERIO DO DESENVOLVIMENTO AGRARIO" ~ "MDA",
org_exec == "MINISTERIO DO DESENVOLVIMENTO REGIONAL" ~ "MDR",
org_exec == "MINISTERIO DO ESPORTE" ~ "Ministério do Esporte",
org_exec == "MINISTERIO DO MEIO AMBIENTE" ~ "Ministério do Meio Ambiente",
org_exec == "MINISTERIO DO TRABALHO" ~ "Ministério do Trabalho",
org_exec == "MINISTERIO DO TRABALHO E EMPREGO" ~ "MTE",
org_exec == "MINISTERIO DO TURISMO" ~ "Ministério do Turismo",
org_exec == "MINISTERIO PUBLICO DA UNIAO" ~ "MPU",
org_exec == "PRESIDENCIA DA REPUBLICA" ~ "Presidência",
org_exec == "SENADO FEDERAL" ~ "Senado Federal",
org_exec == "SUPERIOR TRIBUNAL DE JUSTICA" ~ "STJ",
org_exec == "SUPREMO TRIBUNAL FEDERAL" ~ "STF",
org_exec == "TRIBUNAL DE CONTAS DA UNIAO" ~ "TCU"


  ))


colnames(tg)<- c("fase","fase_cod", "gnd_cod","gnd" , "ano_lan", "ano_emp", "org_uo_cod", "org_uo", "org_exec_cod", "org_exec", "saldo", "org_exec_nome" )

# cria variável data
tg<- tg %>% mutate (ano_lan_2 = ymd(str_c (tg$ano_lan,"/12","/31")))

# https://blog.exploratory.io/5-most-practically-useful-operations-when-working-with-date-and-time-in-r-9f9eb8a17465

colnames(tg)<- c("fase","fase_cod", "gnd_cod","gnd" , "ano_lan", "ano_emp", "org_uo_cod", "org_uo", "org_exec_cod", "org_exec", "saldo", "org_exec_nome", "ano_lan_2" )

```


Selecione o período {.sidebar}
=======================================================================



```{r}

# filtrar período do lançamento
sliderInput("ano_lan", label = h5("ano do lançamento"),
                        min = min(tg$ano_lan), max = max(tg$ano_lan),
                        value = c(min(tg$ano_lan), max = max(tg$ano_lan)),
                        step = 1,
                        round = TRUE)
```






```{r}
#filtrar período do empenho
sliderInput("ano_emp", label = h5("ano do empenho"),
                        min = min(tg$ano_emp), max = max(tg$ano_emp),
                        value = c(min(tg$ano_emp), max = max(tg$ano_emp)),
                        step = 1)
            
```





```{r}
# selecionar órgão

pickerInput(
  inputId = "org_exec", 
  label = "Select/deselect all + format selected", 
  choices = unique(tg$org_exec),
  selected = tg$org_exec,
   options = pickerOptions(
    actionsBox = TRUE,
    selectedTextFormat = "count > 3",
    deselectAllText = "nenhuma",
    selectAllText = "todas",
    liveSearch = TRUE
  ), 
  multiple = TRUE
)

#[https://rdrr.io/cran/shinyWidgets/man/pickerOptions.html]

```




```{r}

# selecionar gnd
pickerInput(
  inputId = "gnd", 
  label = "Select/deselect all + format selected", 
  choices = unique(tg$gnd), 
  selected = tg$gnd,
  
  options = pickerOptions(
    actionsBox = TRUE, 
    selectedTextFormat = "count > 3",
    deselectAllText = "nenhuma",
    selectAllText = "todas"
  ),
  
  multiple = TRUE
)
```


Sequencial
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}



renderPlotly({
 
  # criar tabela para totalizar os valores por fase e ano lançamento
  # tabela tg_total é usada para imprimir o contorno das fases
  tg_total<-tg %>%
  filter( fase != "RP pago",
          ano_emp >=  min(input$ano_emp) & ano_lan <=  max(input$ano_emp),
           ano_lan >=  min(input$ano_lan) & ano_lan <=  max(input$ano_lan))%>%
  group_by(fase, ano_lan_2)%>%
   # transformar para bilhão
     summarise(valor = round(sum(saldo)/1000000000) ,2)
 # incluir texto "_total" na fase para evitar conflito no scale_fill_manual 
 tg_total <- tg_total %>%
 mutate(fase_t = case_when(
 fase == "empenhado" ~ "empenhado_total",
 fase == "liquidado" ~ "liquidado_total",
 fase == "pago" ~ "pago_total",
 fase == "RP pago" ~ "RP pago_total",
 TRUE ~ "outro"
 
))
# criar tabela tg_fases controlada pelos filtros de órgão e gnd.
#  valores da tabela tg_fases são usados para preencher a tabela tg_total
  tg_fase<-tg %>%
  filter( fase != "RP pago",
          ano_emp >=  min(input$ano_emp) & ano_lan <=  max(input$ano_emp),
          org_exec %in% input$org_exec,
          gnd %in% input$gnd,
          ano_lan >=  min(input$ano_lan) & ano_lan <=  max(input$ano_lan))%>%
  group_by(fase, ano_lan_2)%>%
  summarise(valor = round(sum(saldo)/1000000000),2)  
  



p_loa <- ggplot() + 
  # imprime o contorno
  geom_col(data = tg_total, aes( fill = fase_t, y=valor, x=ano_lan_2), alpha = 0.99, color = "gray", position="dodge")+
  # imprime o preenchimento
  geom_col(data = tg_fase, aes(fill= fase, y=valor, x=ano_lan_2), position="dodge")+
  # define as cores
   scale_fill_manual( values = c("empenhado_total" = "#FFFFFF", "liquidado_total" = "#FFFFFF", "pago_total" = "#FFFFFF", "empenhado" = "#5c85d6", "liquidado" = "#1a66ff", "pago" = "#000066"  ))

#[https://community.plot.ly/t/how-to-make-the-messy-date-ticks-organized/7477/3]
#https://help.plot.ly/date-format-and-time-series/
p_loa<-ggplotly(p_loa) %>%
  layout(showlegend = FALSE)%>%
  layout(xaxis = list( tickformat = "%y",
                       title = "", showline = FALSE, showgrid = FALSE ),
         yaxis = list ( title = "", showline = FALSE, showgrid = FALSE ))
p_loa
})
```



row
-----------------------------------------------------------------------



### Chart A

```{r}



renderPlotly({
 
  # criar tabela para totalizar os valores por fase e ano lançamento
  # tabela tg_total é usada para imprimir o contorno das fases
  tg_total<-tg %>%
  filter( fase != "RP pago",
          ano_emp >=  min(input$ano_emp) & ano_lan <=  max(input$ano_emp),
           ano_lan >=  min(input$ano_lan) & ano_lan <=  max(input$ano_lan))%>%
  group_by(fase, ano_lan)%>%
   # transformar para bilhão
     summarise(valor = sum(saldo)/1000000000)
 # incluir texto "_total" na fase para evitar conflito no scale_fill_manual 
 tg_total <- tg_total %>%
 mutate(fase_t = case_when(
 fase == "empenhado" ~ "empenhado_total",
 fase == "liquidado" ~ "liquidado_total",
 fase == "pago" ~ "pago_total",
 fase == "RP pago" ~ "RP pago_total",
 TRUE ~ "outro"
 
))
# criar tabela tg_fases controlada pelos filtros de órgão e gnd.
#  valores da tabela tg_fases são usados para preencher a tabela tg_total
  tg_fase<-tg %>%
  filter( fase != "RP pago",
          ano_emp >=  min(input$ano_emp) & ano_lan <=  max(input$ano_emp),
          org_exec %in% input$org_exec,
          gnd %in% input$gnd,
          ano_lan >=  min(input$ano_lan) & ano_lan <=  max(input$ano_lan))%>%
  group_by(fase, ano_lan)%>%
  summarise(valor = sum(saldo)/1000000000)  
  



p_loa <- ggplot() + 
 
  # imprime o preenchimento
  geom_col(data = tg_fase, aes(fill= fase, y=valor, x=ano_lan), position="dodge")+
  # define as cores
   scale_fill_manual( values = c("empenhado_total" = "#FFFFFF", "liquidado_total" = "#FFFFFF", "pago_total" = "#FFFFFF", "empenhado" = "#5c85d6", "liquidado" = "#1a66ff", "pago" = "#000066"  ))



(p_loa<-ggplotly(p_loa)) %>%
  layout(showlegend = FALSE)%>%
  layout(xaxis = list( title = "", showline = FALSE, showgrid = FALSE ),
         yaxis = list ( title = "", showline = FALSE, showgrid = FALSE ))

})
```




Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
 
 
  # criar tabela para totalizar os valores por fase e ano lançamento
  # tabela tg_total é usada para imprimir o contorno das fases
  tg_total<-tg %>%
  filter( fase != "RP pago",
          ano_emp >=  min(input$ano_emp) & ano_lan <=  max(input$ano_emp),
           ano_lan >=  min(input$ano_lan) & ano_lan <=  max(input$ano_lan))%>%
  group_by(fase, ano_lan)%>%
   # transformar para bilhão
     summarise(valor = sum(saldo)/1000000000)
 # incluir texto "_total" na fase para evitar conflito no scale_fill_manual 
 tg_total <- tg_total %>%
 mutate(fase_t = case_when(
 fase == "empenhado" ~ "empenhado_total",
 fase == "liquidado" ~ "liquidado_total",
 fase == "pago" ~ "pago_total",
 fase == "RP pago" ~ "RP pago_total",
 TRUE ~ "outro"
 
))
# criar tabela tg_fases controlada pelos filtros de órgão e gnd.
#  valores da tabela tg_fases são usados para preencher a tabela tg_total
  tg_fase<-tg %>%
  filter( fase != "RP pago",
          ano_emp >=  min(input$ano_emp) & ano_lan <=  max(input$ano_emp),
          org_exec %in% input$org_exec,
          gnd %in% input$gnd,
          ano_lan >=  min(input$ano_lan) & ano_lan <=  max(input$ano_lan))%>%
  group_by(fase, ano_lan)%>%
  summarise(valor = sum(saldo)/1000000000)  



p_emp <- ggplot() + 
  # imprime linha média
  geom_line(data = tg_total, aes( y= mean(valor), x=ano_lan), alpha = 0.99, color = "gray", position="dodge")+
  # imprime o preenchimento
  geom_col(data = tg_fase, aes(fill= fase, y=valor, x=ano_lan), position="dodge")+
  # define as cores
   scale_fill_manual( values = c("empenhado_total" = "#FFFFFF", "liquidado_total" = "#FFFFFF", "pago_total" = "#FFFFFF", "empenhado" = "#5c85d6", "liquidado" = "#1a66ff", "pago" = "#000066"  ))



(p_emp<-ggplotly(p_emp)) %>%
  layout(showlegend = FALSE)%>%
  layout(xaxis = list( title = "", showline = FALSE, showgrid = FALSE ),
         yaxis = list ( title = "", showline = FALSE, showgrid = FALSE ))

   
  
 
})
```

### Chart C

```{r}



```
